
const Datos = () => {
	const productosIniciales = [
		{
			id: 1,
			nombre: "Remera 1",
			precio: 4500,
			imagen: "/images/101.png",
			category:1,
			item:1,
	
		},
		{
			id: 2,
			nombre: "Remera 2",
			precio: 4200,
			imagen: "/images/107.png",
			category:1,
			item:2,
		},
		{
			id: 3,
			nombre: "Remera 3",
			precio: 4000,
			imagen: "/images/110.png",
			category:1,
			item:3,
		},
		{
			id: 4,
			nombre: "Remera 4",
			precio: 4000,
			imagen: "/images/104.png",
			category:1,
			item:4,
		},
		{
			id: 5,
			nombre: "Remera 5",
			precio: 4000,
			imagen: "/images/109.png",
			category:1,
			item:5,
		},
		{id: 11,
			nombre: "Remera 11",
			precio: 4000,
			imagen: "/images/111.png",
			category:2,
			item:11,
		},
		{id: 12,
			nombre: "Remera 12",
			precio: 4000,
			imagen: "/images/112.png",
			category:2,
			item:12,
		},
		{id: 13,
			nombre: "Remera 13",
			precio: 4000,
			imagen: "/images/113.png",
			category:2,
			item:13,
		},
		{id: 14,
			nombre: "Remera 14",
			precio: 4000,
			imagen: "/images/114.png",
			category:2,
			item:14,
		},
		{id: 15,
			nombre: "Remera 15",
			precio: 4000,
			imagen: "/images/117.png",
			category:2,
			item:15,
		},
	];
    return productosIniciales
};

export default Datos