
const Datos = () => {
	const productosIniciales = [
		{
			id: 1,
			nombre: "Remera Bike Azul",
			precio: 4500,
			imagen: "/images/101.png",
			category:1,
			item:1,
	
		},
		{
			id: 2,
			nombre: "Remera Bike Roja",
			precio: 4500,
			imagen: "/images/102.png",
			category:1,
			item:2,
		},
		{
			id: 3,
			nombre: "Remera Bike Gris",
			precio: 4500,
			imagen: "/images/103.png",
			category:1,
			item:3,
		},
		{
			id: 4,
			nombre: "Remera Bike Naranja",
			precio: 4000,
			imagen: "/images/104.png",
			category:1,
			item:4,
		},
		{
			id: 5,
			nombre: "Remera Tubing Naranja",
			precio: 4000,
			imagen: "/images/105.png",
			category:1,
			item:5,
		},
		{
			id: 6,
			nombre: "Remera Tubing Gris",
			precio: 4000,
			imagen: "/images/106.png",
			category:1,
			item:6,
		},
		{
			id: 7,
			nombre: "Remera Tubing Azul",
			precio: 4200,
			imagen: "/images/107.png",
			category:1,
			item:7,
		},
		{
			id: 8,
			nombre: "Remera Tubing Negra",
			precio: 4200,
			imagen: "/images/108.png",
			category:1,
			item:8,
		},
		{
			id: 9,
			nombre: "Remera Tubing Roja",
			precio: 4200,
			imagen: "/images/109.png",
			category:1,
			item:9,
		},
		{
			id: 10,
			nombre: "Remera Tubing Verde",
			precio: 4000,
			imagen: "/images/110.png",
			category:1,
			item:10,
		},
		
		{id: 11,
			nombre: "Remera 11",
			precio: 4000,
			imagen: "/images/111.png",
			category:2,
			item:11,
		},
		{id: 12,
			nombre: "Remera 12",
			precio: 4000,
			imagen: "/images/112.png",
			category:2,
			item:12,
		},
		{id: 13,
			nombre: "Remera 13",
			precio: 4000,
			imagen: "/images/113.png",
			category:2,
			item:13,
		},
		{id: 14,
			nombre: "Remera 14",
			precio: 4000,
			imagen: "/images/114.png",
			category:2,
			item:14,
		},
		{id: 15,
			nombre: "Remera 15",
			precio: 4000,
			imagen: "/images/115.png",
			category:2,
			item:15,
		},
		{id: 16,
			nombre: "Remera 16",
			precio: 4000,
			imagen: "/images/116.png",
			category:2,
			item:16,
		},
		{id: 17,
			nombre: "Remera 17",
			precio: 4000,
			imagen: "/images/117.png",
			category:2,
			item:17,
		},
		{id: 18,
			nombre: "Remera 18",
			precio: 4000,
			imagen: "/images/118.png",
			category:2,
			item:18,
		},
		{id: 19,
			nombre: "Remera 19",
			precio: 4000,
			imagen: "/images/119.png",
			category:2,
			item:19,
		},
		{id: 20,
			nombre: "Remera 20",
			precio: 4000,
			imagen: "/images/120.png",
			category:2,
			item:20,
		},
		{id: 21,
			nombre: "Remera 21",
			precio: 4000,
			imagen: "/images/121.png",
			category:2,
			item:21,
		},
	];
    return productosIniciales
};

export default Datos